### PR TITLE
neon: Fix Android app switcher background

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/provokateurin/nextcloud-neon/issues/447

### CODE REVIEW

**Comment by Leptopoda** [comment]
Can't we change the android icon itself to do this?
Why should any flutter code get involved?

If we go the route of changing our icons we should make them wiggle as adaptive icons should :)
https://pub.dev/packages/flutter_launcher_icons could be interesting.

**Review by Leptopoda — COMMENTED** [review]
Other than that if we go the way of the PR we should probably move this into a separate variable or getter as the build method is already getting a bit cluttered.

**Comment by provokateurin** [comment]
I need to check out flutter_launcher_icons again, the last time I check it was pretty unmaintained and broken.

**Comment by Leptopoda** [comment]
This was just an idea so we don't have to use it (I last used it a month ago in a production app on iOS/Android and it fit our needs).
But we should consider adding a background to the icon no matter how.

**Comment by provokateurin** [comment]
A problem I see with flutter_launcher_icons is that it only allows to generate a single image so we can't use it to generate the launcher icons for the individual apps. I wanted to move some of the platform specific stuff into the apps (like permissions), maybe this is the moment to attempt that.

**Pull request closed without merging**
