### PR TITLE
Use Result helper methods

### PR DESCRIPTION
**Pull request by provokateurin**
Cleanup after https://github.com/provokateurin/nextcloud-neon/pull/395

### CODE REVIEW

**Review by Leptopoda — APPROVED** [review]
Nice :+1: 

maybe we should also use `requireData` instead of `data!`?

**Comment by provokateurin** [comment]
Ah I forgot to look for those. Let me add them

**Review by Leptopoda — COMMENTED** [review]
we still have some checks (probably only searched for ` !=`)

https://github.com/provokateurin/nextcloud-neon/blob/ed0fe992a00df2238b37be63f136117bd1c7137f/packages/neon/neon_news/lib/widgets/articles_view.dart#L39

**Comment by provokateurin** [comment]
Ah ok, in this case the entire check can be removed. Will search for more occurrences later

**Review by Leptopoda — APPROVED** [review]

**Pull request merged**
