### PR TITLE
Add web support

### PR DESCRIPTION
**Pull request by provokateurin**
Fixes https://github.com/provokateurin/nextcloud-neon/issues/188

### CODE REVIEW

**Review by Leptopoda — APPROVED** [review]
I can't really test this but LGTM

**Comment by Leptopoda** [comment]
Aren't we still hitting the CORS problems?

In this case you might want to remove the `fixe #188` so the issue won't get closed automatically

**Comment by provokateurin** [comment]
Yes we will run into CORS problems, but that is nothing Neon can fix. This is entirely on Nextcloud. I'd say the issue is closed, since it is possible from our side, just not from the server side.

**Comment by provokateurin** [comment]
And it is possible to use some of the APIs, but they need to have CORS manually enabled which most apps don't do (but there are some that do it).

**Pull request merged**
